FROM docker.artifact.${NETWORK_DOMAIN}/infra/devops/node:22-bookworm AS deploy

# RUN apk add --update --no-cache python3=3.12 python3-pip
RUN apt-get install -y python3 python3-pip python3-venv && ln -sf python3 /usr/bin/python

# Configure and upgrade pip, with workaround for weak certificates
RUN pip config --global set global.index https://artifact.${NETWORK_DOMAIN}/artifactory/api/pypi/pypi/simple && \
    pip config --global set global.index-url https://artifact.${NETWORK_DOMAIN}/artifactory/api/pypi/pypi/simple && \
    pip config --global set global.cert /etc/ssl/certs/ca-certificates.crt && \
    pip config --global set global.trusted-host artifact.${NETWORK_DOMAIN} && \
    pip install --upgrade pip

# Set environment variables for Python libraries to use system CA bundle
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt \
    SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt \
    TWINE_CERT=/etc/ssl/certs/ca-certificates.crt

# RUN python3 -m ensurepip
RUN python3 -m venv /opt/venv
RUN /opt/venv/bin/pip3 install --no-cache --upgrade pip setuptools

RUN mkdir /app
RUN mkdir /app/server
RUN mkdir /app/frontend

COPY ./frontend/ /app/frontend/
COPY ./README.md /app/server/README.md
COPY ./pyproject.toml /app/server/pyproject.toml
COPY ./server/ /app/server/
COPY ./entrypoint.sh /app/entrypoint.sh

WORKDIR /app/frontend
RUN npm install

WORKDIR /app/server
RUN /opt/venv/bin/pip3 install .

EXPOSE 8001
EXPOSE 5173

ENV FLASK_ENV=development

WORKDIR /app

#RUN dos2unix entrypoint.sh

CMD ./entrypoint.sh