FROM docker.artifact.${NETWORK_DOMAIN}/infra/devops/python:3.10-slim AS deploy

# env var
ARG NETWORK_DOMAIN
ENV NETWORK_DOMAIN=${NETWORK_DOMAIN}

RUN mkdir /app
RUN mkdir /app/server
RUN mkdir /app/frontend

COPY ./frontend/dist/ /app/frontend/dist
COPY ./pyproject.toml /app/server/pyproject.toml
COPY ./server/ /app/server/

WORKDIR /app/server
RUN pip install .

EXPOSE 8001


WORKDIR /app
CMD ["uvicorn", "server.main:app",  "--host", "0.0.0.0", "--port", "8001", "--reload"]