[project]
name = "scrolly-telling"
version = "0.1.0"
description = ""
authors = [{name = "test", email = "test@example.com"}]
readme = "README.md"
requires-python = ">= 3.8"
dependencies = [
    "fastapi==0.115.0",
    "minio==7.1.13",
    "uvicorn==0.30.6",
    "jinja2==3.1.4"
]
